# Generated by Django 4.0 on 2021-12-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='парковочное место')),
                ('img', models.ImageField(blank=True, upload_to='media')),
                ('is_active', models.BooleanField(default=True, verbose_name='активное')),
            ],
            options={
                'verbose_name_plural': 'Парковочные места',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_field', models.CharField(max_length=32, verbose_name='время для брони')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='main.parkingplaces', verbose_name='парковочное место')),
            ],
            options={
                'verbose_name_plural': 'Время для бронирования парковочных мест',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='дата для брони')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='работник')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parkingplaces', verbose_name='парковочное место')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.time', verbose_name='время бронирования')),
            ],
            options={
                'verbose_name_plural': 'Бронирование парковки',
            },
        ),
    ]
